Repository ManageIQ/manageiq-cross_repo, pull requests merged in 2022-02, with the labels that each got.

#81 Announce the cross repo run information
  lib/manageiq/cross_repo/runner.rb
Labels: enhancement

#83 Replace Travis with Github Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: developer, test

#82 Changes for Github Actions
  .github/workflows/manageiq_cross_repo.yaml
  lib/manageiq/cross_repo/runner.rb
  lib/manageiq/cross_repo/runner/base.rb
  lib/manageiq/cross_repo/runner/github.rb
  lib/manageiq/cross_repo/runner/travis.rb
  spec/manageiq/cross_repo/runner/github_spec.rb
  spec/manageiq/cross_repo/runner/travis_spec.rb
Labels: developer, test

#86 Make test-repos plural in workflow
  .github/workflows/manageiq_cross_repo.yaml
Labels: enhancement

#79 Update node version
  lib/manageiq/cross_repo/runner/base.rb
  spec/manageiq/cross_repo/runner/travis_spec.rb
Labels: dependencies

#89 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
